/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsClass;

import controller.Autentica_login;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Label;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import model.LoginBeans;

/**
 *
 * @author phelype
 */
public class Home extends javax.swing.JFrame {
    public static String j;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        SetarNome();
       // System.out.println("ClassHome" +log);
                  
    
    }
    ///responsavel por setar o nome do usuario logado////
    ////Falta fazer funcionar////////////////////
    public void SetarNome(){
        Login.log = textUser.getName();
        textUser.setEnabled(true);
        Autentica_login a = new Autentica_login();
        textUser.setText("Usuário.: "+a.lo);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnvio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textUser = new javax.swing.JLabel();
        ImagemFundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(150, 150, 150));
        setResizable(false);
        getContentPane().setLayout(null);

        btnEnvio.setBackground(new java.awt.Color(25, 25, 112));
        btnEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSystem/box(1).png"))); // NOI18N
        btnEnvio.setText("Registra Envio");
        btnEnvio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnvio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEnvio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnvio);
        btnEnvio.setBounds(20, 10, 135, 110);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSystem/Expedited-Shipping(3).png"))); // NOI18N
        jButton1.setText("Acompanha Envio");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 10, 140, 110);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSystem/maintenance(1).png"))); // NOI18N
        jButton2.setText("Manutenção");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 10, 140, 110);

        textUser.setText("jLabel2");
        getContentPane().add(textUser);
        textUser.setBounds(20, 260, 140, 16);

        ImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensSystem/hd-solid-color-wallpaper-17.png"))); // NOI18N
        ImagemFundo.setText("Acompanha Envio");
        getContentPane().add(ImagemFundo);
        ImagemFundo.setBounds(0, 0, 630, 290);

        jMenu1.setText("Arquivos");

        jMenuItem1.setText("Usuários");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(617, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        RegistraEnvio reg = new RegistraEnvio();
        reg.setVisible(true);
    }//GEN-LAST:event_btnEnvioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*AcompanhaEnvio ac = new AcompanhaEnvio();
        ac.setVisible(true);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Manutenção manut = new Manutenção();
        manut.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemFundo;
    private javax.swing.JButton btnEnvio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
