package ViewsClass;

import model.EmpresaBeans;
import model.MarcaImpBeans;
import model.ModeloBeans;
import model.TransportadoraBeans;
import controller.CarregaCombos;
import controller.JtextTamanhos;
import controller.cadastros;
import java.awt.Color;
import model.EnviaManutencaoBeans;
import org.w3c.dom.css.RGBColor;
/**
 *
 * @author phelype
 */
public class RegistraEnvio extends javax.swing.JFrame {
    int ini;
    cadastros cad = new cadastros();
    EnviaManutencaoBeans env = new EnviaManutencaoBeans();
    /**
     * Creates new form RegistraEnvio
     */
    public RegistraEnvio() {
        initComponents();
        /////////Set tamanho //////////////////
        textCodigoRemessa.setDocument(new JtextTamanhos(6));
        textPatrimonio.setDocument(new JtextTamanhos(5));
        textSut.setDocument(new JtextTamanhos(5));
        /////////////////////////////////////////////////////
        CarregaCombos combos = new CarregaCombos();

        for (MarcaImpBeans marca : combos.MarcaImp()) {
            comboMarca.setSelectedItem(null);
            comboMarca.addItem(marca);
        }
        for (ModeloBeans model : combos.ModeloImp()) {
            comboModelo.setSelectedItem(null);
            comboModelo.addItem(model);
        }
        for (TransportadoraBeans transpot : combos.Transportadora()) {
            comboTransport.addItem(transpot);
        }
        for (EmpresaBeans emp : combos.ListarEmpresas()) {
            comboDest.addItem(emp);
        }
    }
    ///Variavel que recebe o valor do textCodRemesa////
    String variavel;
    //////////////////////////////////////////////////
    /*public void MesmoCodRemessa() {
                textCodigoRemessa.setText(variavel);
                textCodigoRemessa.setText("");
                comboMarca.setSelectedItem(null);
                comboModelo.setSelectedItem(null);
                textPatrimonio.setText("");
                textSut.setText("");
                textDefeito.setText("");
                textObs.setText("");
                comboTransport.setSelectedItem(null);
                comboDest.setSelectedItem(null);
    }*/
    public void Primeiro(){
        if(textCodigoRemessa.getText().equalsIgnoreCase("") || comboMarca.getSelectedItem() == null ||
                comboModelo.getSelectedItem() == null || textPatrimonio.getText().equalsIgnoreCase("") || textSut.getText().equalsIgnoreCase("") ||
                textDefeito.getText().equalsIgnoreCase("")){
            
            textverificacao.setText("Atenção verifique os campos em branco !");
            textverificacao.setOpaque(false);
            textverificacao.setForeground(Color.red);
            
        }else{
            env.setCod_remesa(Integer.parseInt(textCodigoRemessa.getText()));
            variavel = textCodigoRemessa.getText();
            env.setMdi_imp((MarcaImpBeans) comboMarca.getSelectedItem());
            env.setMdm_id((ModeloBeans) comboModelo.getSelectedItem());
            env.setPatrimonio(Integer.parseInt(textPatrimonio.getText()));
            env.setSut(Integer.parseInt(textSut.getText()));
            env.setDefeito(textDefeito.getText());
            env.setObs(textObs.getText());
            env.setTransporte((TransportadoraBeans) comboTransport.getSelectedItem());
            env.setDestinatario((EmpresaBeans) comboDest.getSelectedItem());
            cad.CadastrarEnvio(env);
            
            textverificacao.setText(cad.aprovado);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textCodigoRemessa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textPatrimonio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDefeito = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textObs = new javax.swing.JTextPane();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        comboDest = new javax.swing.JComboBox<>();
        comboTransport = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        textSut = new javax.swing.JTextField();
        textverificacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Envio");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Código  remessa.:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 16, 110, 17);
        getContentPane().add(textCodigoRemessa);
        textCodigoRemessa.setBounds(158, 10, 130, 29);

        jLabel2.setText("Marca Impressora.:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(14, 55, 120, 17);

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(comboMarca);
        comboMarca.setBounds(158, 49, 130, 29);

        jLabel4.setText("Modelo Impressora.:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(14, 92, 130, 20);

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(comboModelo);
        comboModelo.setBounds(158, 88, 130, 29);

        jLabel5.setText("Patrimônio.:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 133, 80, 17);
        getContentPane().add(textPatrimonio);
        textPatrimonio.setBounds(158, 127, 130, 29);

        jLabel6.setText("Defeito.:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 211, 60, 17);
        getContentPane().add(textDefeito);
        textDefeito.setBounds(158, 205, 130, 29);

        jLabel8.setText("Transporte.:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 250, 80, 17);

        jLabel7.setText("Observações.:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 322, 90, 17);

        jScrollPane1.setViewportView(textObs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 343, 300, 140);

        btnGravar.setText("Gavar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(10, 493, 300, 31);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(10, 532, 300, 31);

        jLabel9.setText("Destinatário.:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 289, 90, 17);

        comboDest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(comboDest);
        comboDest.setBounds(158, 283, 130, 29);

        comboTransport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        getContentPane().add(comboTransport);
        comboTransport.setBounds(158, 244, 130, 29);

        jLabel3.setText("Sut.:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 172, 41, 17);
        getContentPane().add(textSut);
        textSut.setBounds(158, 166, 130, 29);

        textverificacao.setText("Status.:");
        getContentPane().add(textverificacao);
        textverificacao.setBounds(10, 568, 280, 20);

        setSize(new java.awt.Dimension(323, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Primeiro();
        
        textCodigoRemessa.setText(variavel);
        textCodigoRemessa.setBackground(Color.getHSBColor(255, 239, 219));
        comboMarca.setSelectedItem(null);
        comboModelo.setSelectedItem(null);
        textPatrimonio.setText("");
        textSut.setText("");
        textDefeito.setText("");
        textObs.setText("");
        comboTransport.setSelectedItem(null);
        comboDest.setSelectedItem(null);
    }//GEN-LAST:event_btnGravarActionPerformed
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistraEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JComboBox<Object> comboDest;
    private javax.swing.JComboBox<Object> comboMarca;
    private javax.swing.JComboBox<Object> comboModelo;
    private javax.swing.JComboBox<Object> comboTransport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCodigoRemessa;
    private javax.swing.JTextField textDefeito;
    private javax.swing.JTextPane textObs;
    private javax.swing.JTextField textPatrimonio;
    private javax.swing.JTextField textSut;
    private javax.swing.JLabel textverificacao;
    // End of variables declaration//GEN-END:variables
}
